apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitbucket-pipelines-kubernetes-runner.fullname" . }}
  labels:
    {{- include "bitbucket-pipelines-kubernetes-runner.labels" . | nindent 4 }}
spec:
  {{- with .Values.conf }}
  ACCOUNT_UUID: {{ .account_uuid }}
  REPOSITORY_UUID: {{ .repository_uuid }}
  RUNNER_UUID: {{ .runner_uuid }}
  RUNTIME_PREREQUISITES_ENABLED: "true"
  OAUTH_CLIENT_ID: {{ .oauth_client_id }}
  OAUTH_CLIENT_SECRET: {{ .oauth_client_secret }}
  {{- end }}
