image:
  repository: docker.elastic.co/beats/elastic-agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  limits:
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 200Mi

nodeSelector: {}

tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule

affinity: {}

securityContext:
  runAsUser: 0
podSecurityContext: {}
